name: AutoMerge Bot

on:
  pull_request:
    branches: [main]
  ## Temp
  push:
    branches: [merge-test]

env: 
  PR_USER: wtrocki
  APP_SERVICES_CI_TOKEN: ${{ secrets.CI_USER_TOKEN }}
  #PR_USER: app-services-ci

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge changes
    if:  github.actor == '${{ env.PR_USER}}'
    steps:
    - name: Merge Changes
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ env.APP_SERVICES_CI_TOKEN }}